version: '3'

services:
  server:
    build:
      context: .
    ports:
      - "9000:9000"
    depends_on:
      - database
    environment:
      MONGODB_URI: "mongodb+srv://shopify-next-test:6hDqCorGy1vEGBAQ@cluster0.mpabhrs.mongodb.net/?retryWrites=true&majority&appName=Cluster0"

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
